name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  build:
    environment: production
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Den4200/kubernetes
          token: ${{ secrets.KUBE_REPO_TOKEN }}

      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          namespace: audreyasked
          manifests: |
            audreyasked/audreyasked/deployment.yaml
          images: |
            ghcr.io/den4200/audreyasked:${{ steps.sha_tag.outputs.tag }}
          kubectl-version: 'latest'
