name: Lint

on:
  push:
    branches:
      - main
  pull_request_target:

permissions:
  checks: write
  contents: read

jobs:
  lint:
    name: Setup Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - name: Checkout repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: Install Node.js dependencies
        run: yarn install

      - name: Lint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
